export interface GlossaryEntry {
  slug: string;           // URL-safe slug, used as anchor on /glossary
  term: string;           // display term
  aliases?: string[];     // alternative phrasings (case-insensitive match for auto-lookup)
  category: 'hardware-analog' | 'framework' | 'methodology' | 'web';
  tooltip: string;        // short definition for the hover popover (≤ 20 words)
  full: string;           // long definition for the glossary page (1-2 sentences, plain language)
}

export const GLOSSARY: GlossaryEntry[] = [
  // --- Hardware analogs (the source concepts for the framework's SoC-inspired design) ---
  {
    slug: 'soc',
    term: 'SoC (System on Chip)',
    aliases: ['SoC', 'System on Chip', 'system-on-chip'],
    category: 'hardware-analog',
    tooltip: "A chip that packs CPU, GPU, memory, and more onto one silicon die — inspired this framework's layered design.",
    full: "A System on Chip integrates the CPU, GPU, memory controllers, and specialized accelerators onto a single piece of silicon. Modern mobile processors (Apple M-series, Snapdragon, etc.) are SoCs. The fitme-story framework borrowed seven organizing principles from SoC design — skill-on-demand loading, cache tiers, systolic execution, dispatch intelligence — and applied them to a software PM workflow.",
  },
  {
    slug: 'systolic-chain',
    term: 'Systolic chain',
    aliases: ['systolic chain', 'systolic array'],
    category: 'hardware-analog',
    tooltip: 'A TPU pattern where data flows from one processing cell to the next without round-trips to memory.',
    full: 'In a TPU (Tensor Processing Unit), a systolic array is a grid of processing cells that pass data directly to their neighbors, avoiding expensive memory round-trips. The framework applies the same pattern inside a single task: Grep → Read → Edit chains forward results without re-reading files, cutting dispatch cycles dramatically.',
  },
  {
    slug: 'lora-hot-swap',
    term: 'LoRA hot-swap',
    aliases: ['LoRA', 'LoRA adapter', 'LoRA hot-swap'],
    category: 'hardware-analog',
    tooltip: 'A pattern where small task-specific adapters swap in and out of a base model on demand.',
    full: "LoRA (Low-Rank Adaptation) is a technique for attaching tiny task-specific weight adapters to a large model without retraining the full thing. The framework borrowed this idea for \"skill-on-demand\" — only the skills relevant to the current phase are loaded into the agent's context, not all eleven at once.",
  },
  {
    slug: 'palettization',
    term: 'Palettization (weight compression)',
    aliases: ['palettization', 'weight palettization'],
    category: 'hardware-analog',
    tooltip: 'A ~3.7-bit compression format that shrinks neural network weights with minimal accuracy loss.',
    full: 'Palettization quantizes neural network weights down to ~3.7 bits per value (from 32 or 16), dramatically reducing model size with minimal accuracy impact. The framework applied the same compress-then-decompress pattern to its cache entries, reclaiming roughly 24K tokens of context window per session.',
  },
  {
    slug: 'big-little',
    term: 'big.LITTLE',
    aliases: ['big.LITTLE', 'big-LITTLE', 'heterogeneous cores'],
    category: 'hardware-analog',
    tooltip: "ARM's heterogeneous design: fast \"big\" cores for heavy work, efficient \"LITTLE\" cores for light work.",
    full: "ARM's big.LITTLE architecture pairs high-performance \"big\" cores with energy-efficient \"LITTLE\" cores. The OS routes tasks to whichever core fits. The framework applies the same idea: a task_complexity_gate routes mechanical work to a cheap \"LITTLE\" model and complex work to a capable \"big\" one.",
  },
  {
    slug: 'ane-mixed-precision',
    term: 'ANE mixed-precision',
    aliases: ['ANE', 'Apple Neural Engine'],
    category: 'hardware-analog',
    tooltip: "Apple's neural engine mixes 8-bit and 16-bit math to trade accuracy for speed.",
    full: 'The Apple Neural Engine (ANE) runs different layers of a model at different precisions — cheap layers at 8-bit, critical ones at 16-bit. The framework adopted the same pattern for its model_tiering: cheap skills and simple tasks run on smaller models, reserving bigger models for work that actually needs them.',
  },
  {
    slug: 'uma-zero-copy',
    term: 'Unified Memory Architecture (UMA)',
    aliases: ['UMA', 'Unified Memory'],
    category: 'hardware-analog',
    tooltip: "Apple Silicon's shared CPU/GPU memory — no copying data between components.",
    full: "On Apple Silicon, the CPU and GPU share a single pool of unified memory. There's no expensive copying data between them. The framework mirrors this with \"result forwarding\": the output of one skill is handed to the next without a write-then-re-read cycle.",
  },
  {
    slug: 'speculative-preload',
    term: 'Speculative preload',
    aliases: ['speculative preload', 'branch prediction'],
    category: 'hardware-analog',
    tooltip: 'A CPU pattern that pre-fetches likely-next instructions to avoid wait cycles.',
    full: "Modern CPUs predict which branch of an if/else they'll take and pre-fetch the likely instructions before the actual decision lands. The framework does the analog for skills: while Phase 4 runs, it speculatively preloads the probable Phase 5 skills into context, so the transition is zero-wait.",
  },
  {
    slug: 'tpu',
    term: 'TPU (Tensor Processing Unit)',
    aliases: ['TPU'],
    category: 'hardware-analog',
    tooltip: "Google's custom chip for matrix math — the source of the systolic-array dataflow pattern.",
    full: "Tensor Processing Units are Google-designed accelerators optimized for the matrix multiplications at the core of neural networks. The framework borrowed two TPU ideas: systolic dataflow (data passes cell-to-cell) and weight-stationary batch dispatch (reuse loaded weights across many inputs).",
  },
  {
    slug: 'mahalanobis-distance',
    term: 'Mahalanobis distance',
    aliases: ['Mahalanobis'],
    category: 'hardware-analog',
    tooltip: 'A statistical distance metric that accounts for how measurements correlate with each other.',
    full: "Mahalanobis distance measures how far one point is from a cluster of other points, taking into account how correlated the different dimensions are. The framework's V7.0 HADF (Hardware-Aware Dispatch) uses it to match a running environment's performance fingerprint to the closest chip profile in its library of 17 chips.",
  },

  // --- Framework components ---
  {
    slug: 'pm-workflow',
    term: '/pm-workflow',
    aliases: ['pm-workflow', 'PM workflow', '/pm-workflow'],
    category: 'framework',
    tooltip: 'The root Claude Code skill that orchestrates a feature through nine lifecycle phases.',
    full: 'The /pm-workflow skill is the orchestrator at the heart of the framework. It enforces a nine-phase lifecycle — Research → PRD → Tasks → UX → Implement → Test → Review → Merge → Docs — with approval gates between each phase. Other skills (dev, qa, design, etc.) are invoked from inside pm-workflow as needed.',
  },
  {
    slug: 'dispatch-intelligence',
    term: 'Dispatch intelligence',
    aliases: ['dispatch intelligence', 'dispatch'],
    category: 'framework',
    tooltip: 'A three-stage pipeline that classifies a task, picks a model tier, and allocates a tool budget.',
    full: 'Dispatch intelligence is the Floor 5 component that looks at an incoming task and makes three decisions before work starts: how complex is this (complexity_scoring), which model tier runs it (model_routing, LITTLE vs big), and how many tool calls is it allowed (tool_budgets). Together these cut wasted dispatch by roughly 48%.',
  },
  {
    slug: 'skill-on-demand',
    term: 'Skill-on-demand loading',
    aliases: ['skill-on-demand', 'on-demand loading'],
    category: 'framework',
    tooltip: 'Loading only the skills needed for the current phase instead of all 11 upfront.',
    full: "Rather than load all eleven skill files into context at session start (which ate ~48% of the context window), the framework loads only the 1–2 skills relevant to the current phase. Inspired by LoRA hot-swap in neural networks. Reclaims ~30K tokens per session.",
  },
  {
    slug: 'cache-tiers',
    term: 'Cache tiers (L1 / L2 / L3)',
    aliases: ['L1', 'L2', 'L3', 'cache tiers', 'L1 cache', 'L2 cache', 'L3 cache'],
    category: 'framework',
    tooltip: 'Three-level cache: L1 per-skill, L2 shared, L3 project-wide — borrowed from CPU architecture.',
    full: 'Exactly like CPU caches, the framework keeps frequently-accessed context close and rarely-accessed context further away. L1 is per-skill and fastest to hit. L2 (`_shared/`) holds cross-skill patterns. L3 (`_project/`) holds project-wide lore. Hit rates are instrumented in cache-hits.json.',
  },
  {
    slug: 'hub-and-spoke',
    term: 'Hub-and-spoke topology',
    aliases: ['hub-and-spoke', 'hub and spoke'],
    category: 'framework',
    tooltip: 'pm-workflow as the central hub that delegates to domain skills as spokes.',
    full: 'The framework is organized as a hub-and-spoke graph: /pm-workflow is the root orchestrator, and domain skills (dev, design, qa, analytics, etc.) are spokes invoked from the hub based on phase and task type. The topology emerged at v4.3 and produced a 6.5x speedup over the previous mesh.',
  },
  {
    slug: 'hadf',
    term: 'V7.0 HADF (Hardware-Aware Dispatch Framework)',
    aliases: ['V7.0 HADF', 'HADF', 'Hardware-Aware Dispatch', 'hardware-aware dispatch'],
    category: 'framework',
    tooltip: "V7.0 HADF detects the chip it's running on and adjusts dispatch accordingly.",
    full: "V7.0 HADF extends the dispatch layer with a hardware awareness stage. It detects the chip/runtime fingerprint via OS APIs and Mahalanobis distance matching against 17 chip profiles + 7 cloud signatures, then adjusts model routing and cache strategy for the detected environment. Ships as framework version 7.0.",
  },
  {
    slug: 'complexity-units',
    term: 'Complexity Units (CU)',
    aliases: ['CU', 'Complexity Units', 'CU formula', 'CU v2'],
    category: 'framework',
    tooltip: 'A normalized complexity score used to compare velocity across very different features.',
    full: 'Complexity Units are a normalized measurement that lets the framework compare the velocity of features as different as "fix a typo" and "build a hardware-aware dispatch layer." The v2 formula (power-law fit, R²=0.82) accounts for view count, type count, and design iteration scope.',
  },
  {
    slug: 'phase-timing',
    term: 'Phase timing',
    aliases: ['phase timing', 'phase-timing.json'],
    category: 'framework',
    tooltip: 'Automatic instrumentation of how long each phase takes — replaces subjective estimates.',
    full: 'Every phase transition is timestamped and recorded in phase-timing.json. Replaces the old "±15-30 min estimates" with real, retrospective data. Introduced in framework v6.0 as part of the measurement overlay.',
  },
  {
    slug: 'parallel-write-safety',
    term: 'Parallel write safety',
    aliases: ['parallel write safety', 'mirror pattern', 'snapshot/rollback'],
    category: 'framework',
    tooltip: 'Keeps parallel subagents from clobbering each other via snapshot/rollback + mirror pattern.',
    full: 'When multiple subagents work in parallel, they can write to the same files. Parallel write safety prevents corruption: each subagent works on a mirror of the file, snapshots the original, and rolls back if the build fails. Part of framework v5.2.',
  },
  {
    slug: 'eval-layer',
    term: 'Eval layer',
    aliases: ['eval layer', 'evaluation layer', 'golden I/O'],
    category: 'framework',
    tooltip: "A test suite using golden input/output pairs that gates AI-producing phases.",
    full: "The eval layer is the framework's formalized test-before-merge step for AI-generated output. A library of golden I/O pairs (known input, expected output) runs before any \"AI produced\" phase can advance. Coverage below a threshold blocks the phase. Introduced in v4.4.",
  },
  {
    slug: 'snapshot-rollback',
    term: 'Snapshot / rollback',
    aliases: ['snapshot', 'rollback', 'snapshot/rollback'],
    category: 'framework',
    tooltip: 'Automatic file-state backup that auto-restores when a build fails.',
    full: "Before any risky write operation, the framework snapshots the current file state to a side store. If the subsequent build or test fails, rollback auto-restores from the snapshot. Prevents half-applied changes from corrupting main. Part of v5.2's parallel write safety.",
  },
  {
    slug: 'task-complexity-gate',
    term: 'Task complexity gate',
    aliases: ['task complexity gate', 'task_complexity_gate'],
    category: 'framework',
    tooltip: 'The routing stage that decides whether a task runs on a cheap or capable model.',
    full: "At dispatch time, the task complexity gate inspects the task and routes it to either a \"LITTLE\" (cheap, fast) or \"big\" (capable, slower) model. Mechanical token migrations go to LITTLE; architectural rewrites go to big. Modeled on ARM's big.LITTLE.",
  },
  {
    slug: 'batch-dispatch',
    term: 'Batch dispatch',
    aliases: ['batch dispatch', 'batched dispatch'],
    category: 'framework',
    tooltip: 'Grouping tightly-coupled tasks into a single subagent call instead of dispatching one by one.',
    full: 'Rather than dispatch each task to its own subagent (high orchestration overhead), batch dispatch groups coupled tasks — e.g. four component files that change together — into a single subagent call that commits per task. Modeled on TPU weight-stationary: load the context once, run many small ops on it.',
  },
  {
    slug: 'result-forwarding',
    term: 'Result forwarding',
    aliases: ['result forwarding'],
    category: 'framework',
    tooltip: "Passing one skill's output directly to the next without writing, then re-reading.",
    full: "When Skill A's output is Skill B's input, result forwarding passes it in memory rather than serializing through a file. Modeled on Apple Silicon's unified memory architecture. Eliminates the classic write-then-re-read cycle.",
  },

  // --- Methodology ---
  {
    slug: 'case-study-monitoring',
    term: 'Case study monitoring',
    aliases: ['case study monitoring', 'case-study-monitoring'],
    category: 'methodology',
    tooltip: "Every feature opens a data-collection entry that's used to write a real case study afterward.",
    full: 'The case-study-monitoring.json file records process metrics, quality metrics, success cases, and failure cases for every feature run through the framework. These records become the source material for real case studies — no invented numbers.',
  },
  {
    slug: 'normalization',
    term: 'Normalization (R²=0.82)',
    aliases: ['normalization', 'R²=0.82', 'normalization formula'],
    category: 'methodology',
    tooltip: "A power-law fit (R²=0.82) used to compare feature velocity across very different features.",
    full: "Not all features are the same size. The framework's normalization model uses a retroactive power-law fit (R²=0.82 across all prior features) to translate raw minutes-to-ship into comparable Complexity-Unit rates, so a ten-minute typo fix and a two-hour new feature sit on the same scale.",
  },
  {
    slug: 'audit-findings',
    term: 'Audit findings',
    aliases: ['audit findings', 'findings'],
    category: 'methodology',
    tooltip: 'Defects and gaps surfaced during full-system audits — tracked, prioritized, fixed.',
    full: 'When the framework audits itself (every few months), it produces findings: typed issues with severity (critical / high / medium / low) and domain. The v7.0 audit produced 185 findings, 12 critical. Every finding is publicly tracked, addressed, and closed out in a sprint.',
  },

  // --- Web vitals ---
  {
    slug: 'lcp',
    term: 'LCP (Largest Contentful Paint)',
    aliases: ['LCP', 'Largest Contentful Paint'],
    category: 'web',
    tooltip: 'How long until the main visible content of a page finishes rendering.',
    full: "One of Google's Core Web Vitals. LCP measures when the largest visible element (often the hero image or headline) finishes rendering. Under 2.5 seconds is \"good.\" This site targets under 1 second on desktop.",
  },
  {
    slug: 'cls',
    term: 'CLS (Cumulative Layout Shift)',
    aliases: ['CLS', 'Cumulative Layout Shift'],
    category: 'web',
    tooltip: 'How much the page jumps around after initial paint — a measure of layout stability.',
    full: 'CLS tracks how much visible content shifts position unexpectedly during page load (e.g. images loading, fonts swapping). Under 0.1 is "good." Low CLS is important for accessibility — moving targets frustrate users with motor impairments.',
  },
  {
    slug: 'ssg',
    term: 'Static Site Generation (SSG)',
    aliases: ['SSG', 'static generation', 'Static Site Generation'],
    category: 'web',
    tooltip: 'Pre-rendering every page to HTML at build time — fast, cacheable, no runtime database hits.',
    full: "Rather than render pages on each request (server-side rendering) or only on the client (SPA), SSG pre-computes every page's HTML at build time and serves it as a static file. fitme-story uses Next.js App Router's SSG for all 38 routes — 0ms server work at request time.",
  },
];
